{{- if .Values.enabled }}
apiVersion: v1
data:
  AUTH0_TOKEN: {{ .Values.variables.AUTH0_TOKEN | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Release.Namespace }}
{{- end }}
