{{- if .Values.enabled }}
apiVersion: v1
data:
  TOKEN: {{ .Values.variables.TOKEN | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Release.Namespace }}
{{- end }}
