{{- if .Values.enabled }}
{{- $values := .Values -}}
{{- $release := .Release -}}
{{- range .Values.permissions -}}
  {{- if eq .namespace "*" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $values.name }}-{{ $release.Namespace }}-{{ $release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $values.name }}
subjects:
  - kind: ServiceAccount
    name: {{ $values.name }}-sa
    namespace: {{ $release.Namespace }}
{{- end -}}
{{- end -}}
{{- end }}
