{{- if .Values.enabled }}
{{- $apiGroupMapping := (include "apiGroupMapping" . | fromJson) }}
{{- $values := .Values -}}
{{- range $values.permissions -}}
  {{- if ne .namespace "*" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $values.name }}
  namespace: {{ .namespace }}
rules:
  {{- range $key, $verbs := . }}
    {{- if and (ne $key "namespace") $verbs }}
  - apiGroups: {{ (index $apiGroupMapping $key) | toJson }}
    resources: ["{{ $key }}"]
    verbs: {{ $verbs | toJson }}
    {{- end }}
  {{- end }}
  {{- end -}}
{{- end -}}
{{- end }}
