{{- if .Values.enabled }}
{{- $values := .Values -}}
{{- $release := .Release -}}
{{- range .Values.permissions -}}
  {{- if ne .namespace "*" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $values.name }}-{{ $release.Namespace }}-{{ $release.Name }}
  namespace: {{ .namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $values.name }}-{{ $release.Namespace }}-{{ $release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ $values.name }}-sa
    namespace: {{ $release.Namespace }}
{{- end -}}
{{- end -}}
{{- end }}
